ARG VERSION=latest

FROM b3log/siyuan:${VERSION}

RUN apk update && apk add --no-cache --update tesseract-ocr

RUN cd /usr/share/tessdata \
	&& wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata \
	&& wget https://github.com/tesseract-ocr/tessdata/raw/main/chi_sim.traineddata \
	&& wget https://github.com/tesseract-ocr/tessdata/raw/main/chi_tra.traineddata
	# Add more langs if needed

ENTRYPOINT ["/opt/siyuan/entrypoint.sh"]

CMD ["/opt/siyuan/kernel"]
